### ISSUE TITLE
Handle and throw library error instead

### ISSUE THREAD

**Issue by regaw-leinad** [regaw-leinad/winix-api#2]
when a refresh token is expired, let's throw our own library error so the client code can catch and prompt the user to login again

```
[2/28/2024, 4:06:22 AM] [WinixPurifiers] error generating winix account from existing auth: NotAuthorizedException: Refresh Token has expired
    at de_NotAuthorizedExceptionRes (/homebridge/node_modules/homebridge-winix-purifiers/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/index.js:4077:21)
    at de_CommandError (/homebridge/node_modules/homebridge-winix-purifiers/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/index.js:3770:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /homebridge/node_modules/homebridge-winix-purifiers/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at /homebridge/node_modules/homebridge-winix-purifiers/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at /homebridge/node_modules/homebridge-winix-purifiers/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at /homebridge/node_modules/homebridge-winix-purifiers/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at Function.refresh (/homebridge/node_modules/homebridge-winix-purifiers/node_modules/winix-api/dist/account/winix-auth.js:34:26)
    at Function.fromExistingAuth (/homebridge/node_modules/homebridge-winix-purifiers/node_modules/winix-api/dist/account/winix-account.js:37:22)
    at WinixPurifierPlatform.onFinishLaunching (/homebridge/node_modules/homebridge-winix-purifiers/dist/platform.js:32:26) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'ca4bd4b7-d21a-4c67-8844-9934bd202e71',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'NotAuthorizedException'
}
```

**Comment by regaw-leinad** [comment]
yes, this stack trace is from https://github.com/regaw-leinad/homebridge-winix-purifiers, but the error propagates from this library, and I want to handle a bit more gracefully here
